# Generated by Django 4.1.7 on 2023-02-26 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0008_alter_cafedra_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Fan nomi')),
                ('cafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.cafedra', verbose_name='Kafedrasi')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': '1. Barcha fanlar',
            },
        ),
    ]
