# Generated by Django 4.1.7 on 2023-02-26 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_cafedra_options_and_more'),
        ('study_plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yunalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Yo'nalish nomi")),
                ('language', models.CharField(choices=[('uzbek', "O'zbek"), ('rus', 'Rus'), ('other', 'Boshqa')], max_length=10, verbose_name="Ta'lim tili")),
                ('study_shape', models.CharField(choices=[('kunduzgi', 'kunduzgi'), ('kechki', 'kechki'), ('sirtqi', 'sirtqi')], max_length=10, verbose_name="Ta'lim shakli")),
                ('year', models.IntegerField(verbose_name='Qabul qilingan yili')),
                ('study_year', models.FloatField(verbose_name="O'qish muddati")),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.faculty', verbose_name='Fakulteti')),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "2. Barcha yo'nalishlar",
            },
        ),
        migrations.CreateModel(
            name='SemestrStudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_semestr', models.IntegerField(verbose_name='Semestr raqami')),
                ('yunalish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_plan.yunalish', verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': 'Semestr rejasi',
                'verbose_name_plural': '3. Semestr rejalari',
            },
        ),
    ]
