# Generated by Django 4.1.7 on 2023-02-26 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0002_yunalish_semestrstudyplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='cafedra',
        ),
        migrations.RemoveField(
            model_name='yunalish',
            name='faculty',
        ),
        migrations.DeleteModel(
            name='SemestrStudyPlan',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Yunalish',
        ),
    ]
