# Generated by Django 4.1.7 on 2023-02-26 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0005_delete_sciencestudyplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScienceStudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('science_code', models.CharField(max_length=30, verbose_name='Fan kodi')),
                ('exam_type', models.CharField(choices=[('imtihon', 'imtihon'), ('sinov', 'sinov')], max_length=10, verbose_name='Sinov turi')),
                ('credit', models.IntegerField(verbose_name='Kredit miqdori')),
                ('lecture', models.IntegerField(default=0, verbose_name="Ma'ruza vaqti")),
                ('practice', models.IntegerField(default=0, verbose_name='Amaliyot vaqti')),
                ('seminar', models.IntegerField(default=0, verbose_name='Seminar vaqti')),
                ('laboratory', models.IntegerField(default=0, verbose_name='Labaratoriya vaqti')),
                ('independent_work', models.IntegerField(verbose_name='Mustaqil ish vaqti')),
                ('course_work', models.BooleanField(default=False, verbose_name='Kurs ishi')),
                ('science', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_plan.science', verbose_name='Fan')),
                ('semestr_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_plan.semestrstudyplan', verbose_name='Semestr rejasi')),
            ],
            options={
                'verbose_name': "O'quv reja fani",
                'verbose_name_plural': "4. O'quv reja fanlari",
            },
        ),
    ]
