# Generated by Django 4.1.7 on 2023-02-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Lavozim nomi')),
                ('short_name', models.CharField(max_length=100, verbose_name='Lavozimning qisqa nomi')),
            ],
            options={
                'verbose_name': 'Dekanat lavozimi',
                'verbose_name_plural': 'Dekanat lavozimlari',
            },
        ),
        migrations.AddField(
            model_name='mainuser',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Otasining ismi'),
        ),
    ]
