# Generated by Django 4.1.7 on 2023-02-24 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_leadershipposition_mainuser_father_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.leadershipposition', verbose_name='Lavozimi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Rahbar',
                'verbose_name_plural': '2. Rahbarlar',
            },
        ),
    ]
