# Generated by Django 4.1.7 on 2023-02-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_leadership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadershipposition',
            name='short_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Lavozimning qisqa nomi'),
        ),
    ]
