# Generated by Django 4.1.7 on 2023-02-26 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_leadershipposition_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Fakultet',
                'verbose_name_plural': '3. Fakultetlar',
            },
        ),
        migrations.CreateModel(
            name='PositionEmployeeFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Lavozim')),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lavozim (qisqa nomi)')),
            ],
            options={
                'verbose_name': 'Fakultet lavozimi',
                'verbose_name_plural': '2. Fakultet lavozimlari',
            },
        ),
        migrations.CreateModel(
            name='FacultyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.faculty', verbose_name='Fakultet nomi')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.positionemployeefaculty', verbose_name='Darajasi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Fakultet hodimi',
                'verbose_name_plural': '4. Fakultet hodimlari',
            },
        ),
    ]
