# Generated by Django 4.1.7 on 2023-02-26 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_cafedramember_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafedra',
            options={'verbose_name': 'Kafedra', 'verbose_name_plural': '5. Kafedralar'},
        ),
        migrations.AlterModelOptions(
            name='cafedraemployeeposition',
            options={'verbose_name': 'Kafedra lavozimi', 'verbose_name_plural': 'Kafedra lavozimlari (<=>)'},
        ),
        migrations.AlterModelOptions(
            name='cafedramember',
            options={'verbose_name': 'Kafedra hodimi', 'verbose_name_plural': '6. Kafedra hodimlari'},
        ),
        migrations.AlterModelOptions(
            name='leadershipposition',
            options={'verbose_name': 'Dekanat lavozimi', 'verbose_name_plural': 'Dekanat lavozimlari (<=>)'},
        ),
        migrations.AlterModelOptions(
            name='positionemployeefaculty',
            options={'verbose_name': 'Fakultet lavozimi', 'verbose_name_plural': 'Fakultet lavozimlari (<=>)'},
        ),
    ]
